version: '3'

services:
    springbootapp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: unless-stopped
        depends_on:
            - db
        links:
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"

    redis:
        image: redis
        ports:
            - "6379:6379"
    